### ISSUE TITLE
Onboarding of the whole Deutch Team on the Catalog service

### ISSUE THREAD

**Issue by sasadangelo** [sasadangelo/chattery_issue#78]
The following members must request Access via AccessHUB on the tls-platform-ai application. Then he should wait for 1st line manager and service owner approval. Hans Muller, Klaus Schmidt, and Ursula Bauer.

**Comment by SAMBILI** [comment]
I think this will help you.
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme

you may need to install the c compiler
